//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenerConfigurator.ClientCore.Utilities.MUI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GreenerConfigurator.Utilities.MUI.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        public static string Activate {
            get {
                return ResourceManager.GetString("Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Time.
        /// </summary>
        public static string ActiveTime {
            get {
                return ResourceManager.GetString("ActiveTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Time List.
        /// </summary>
        public static string ActiveTimeList {
            get {
                return ResourceManager.GetString("ActiveTimeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Device Info.
        /// </summary>
        public static string AddDeviceInfo {
            get {
                return ResourceManager.GetString("AddDeviceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Location/Location Detail.
        /// </summary>
        public static string AddLocationAndDetail {
            get {
                return ResourceManager.GetString("AddLocationAndDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Unassinged NetworkDevices.
        /// </summary>
        public static string AddUnassingedNetworkDevice {
            get {
                return ResourceManager.GetString("AddUnassingedNetworkDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Without Location Information.
        /// </summary>
        public static string AddWithNoLocation {
            get {
                return ResourceManager.GetString("AddWithNoLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alarm Level.
        /// </summary>
        public static string AlarmLevel {
            get {
                return ResourceManager.GetString("AlarmLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert Notification.
        /// </summary>
        public static string AlertNotification {
            get {
                return ResourceManager.GetString("AlertNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Days.
        /// </summary>
        public static string AllDays {
            get {
                return ResourceManager.GetString("AllDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Filter.
        /// </summary>
        public static string ApplyFilter {
            get {
                return ResourceManager.GetString("ApplyFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Category.
        /// </summary>
        public static string AssginCategory {
            get {
                return ResourceManager.GetString("AssginCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Categories List.
        /// </summary>
        public static string AssignedCategoriesList {
            get {
                return ResourceManager.GetString("AssignedCategoriesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Categories List.
        /// </summary>
        public static string AvailableCategoriesList {
            get {
                return ResourceManager.GetString("AvailableCategoriesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus/Network Type.
        /// </summary>
        public static string Bus_NetworkType {
            get {
                return ResourceManager.GetString("Bus/NetworkType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus Connection.
        /// </summary>
        public static string BusConnection {
            get {
                return ResourceManager.GetString("BusConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus Connection Interface Type.
        /// </summary>
        public static string BusConnectionInterfaceType {
            get {
                return ResourceManager.GetString("BusConnectionInterfaceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus Connection List.
        /// </summary>
        public static string BusConnectionList {
            get {
                return ResourceManager.GetString("BusConnectionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare Condition.
        /// </summary>
        public static string CompareCondition {
            get {
                return ResourceManager.GetString("CompareCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare Operator Type.
        /// </summary>
        public static string CompareOperatorType {
            get {
                return ResourceManager.GetString("CompareOperatorType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Gateway.
        /// </summary>
        public static string ConfigureGateway {
            get {
                return ResourceManager.GetString("ConfigureGateway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure manually.
        /// </summary>
        public static string ConfigureManually {
            get {
                return ResourceManager.GetString("ConfigureManually", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection View.
        /// </summary>
        public static string ConnectionView {
            get {
                return ResourceManager.GetString("ConnectionView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Code.
        /// </summary>
        public static string CountryCode {
            get {
                return ResourceManager.GetString("CountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current User:.
        /// </summary>
        public static string CurrentUser {
            get {
                return ResourceManager.GetString("CurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Detail Number.
        /// </summary>
        public static string DataDetailNumber {
            get {
                return ResourceManager.GetString("DataDetailNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days Of The Week.
        /// </summary>
        public static string DaysOfTheWeek {
            get {
                return ResourceManager.GetString("DaysOfTheWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Name.
        /// </summary>
        public static string DeviceName {
            get {
                return ResourceManager.GetString("DeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Password.
        /// </summary>
        public static string DevicePassword {
            get {
                return ResourceManager.GetString("DevicePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Management.
        /// </summary>
        public static string DocumentManagement {
            get {
                return ResourceManager.GetString("DocumentManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Detail Number.
        /// </summary>
        public static string ExchangeDetailNumber {
            get {
                return ResourceManager.GetString("ExchangeDetailNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        public static string FileName {
            get {
                return ResourceManager.GetString("FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter By Bridge.
        /// </summary>
        public static string FilterByBridgeDevice {
            get {
                return ResourceManager.GetString("FilterByBridgeDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter By Gateway.
        /// </summary>
        public static string FilterByGatewayDevice {
            get {
                return ResourceManager.GetString("FilterByGatewayDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter By Location.
        /// </summary>
        public static string FilterByLocation {
            get {
                return ResourceManager.GetString("FilterByLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter By Location Detail.
        /// </summary>
        public static string FilterByLocationDetail {
            get {
                return ResourceManager.GetString("FilterByLocationDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter By NoLocation Data.
        /// </summary>
        public static string FilterByNoLocation {
            get {
                return ResourceManager.GetString("FilterByNoLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show All.
        /// </summary>
        public static string FilterShowAll {
            get {
                return ResourceManager.GetString("FilterShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First.
        /// </summary>
        public static string First {
            get {
                return ResourceManager.GetString("First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Compare Condition List.
        /// </summary>
        public static string FirstCompareConditionList {
            get {
                return ResourceManager.GetString("FirstCompareConditionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friday.
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date.
        /// </summary>
        public static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date Every Year.
        /// </summary>
        public static string FromDateEveryYear {
            get {
                return ResourceManager.GetString("FromDateEveryYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Time.
        /// </summary>
        public static string FromTime {
            get {
                return ResourceManager.GetString("FromTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gateway and Bridges Management.
        /// </summary>
        public static string GatewayBridgesManagement {
            get {
                return ResourceManager.GetString("GatewayBridgesManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GatewayConnection.
        /// </summary>
        public static string GatewayConnection {
            get {
                return ResourceManager.GetString("GatewayConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greener Configurator.
        /// </summary>
        public static string GreenerConfigurator {
            get {
                return ResourceManager.GetString("GreenerConfigurator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grouped Navigation Card List.
        /// </summary>
        public static string GroupedNavigationCardList {
            get {
                return ResourceManager.GetString("GroupedNavigationCardList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Details.
        /// </summary>
        public static string HideDetails {
            get {
                return ResourceManager.GetString("HideDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IccdId is not valid.
        /// </summary>
        public static string IccdIdIsNotValid {
            get {
                return ResourceManager.GetString("IccdIdIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IccId.
        /// </summary>
        public static string IccId {
            get {
                return ResourceManager.GetString("IccId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IMEI.
        /// </summary>
        public static string IMEI {
            get {
                return ResourceManager.GetString("IMEI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import sensors.
        /// </summary>
        public static string ImportSensors {
            get {
                return ResourceManager.GetString("ImportSensors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info Notification.
        /// </summary>
        public static string InfoNotification {
            get {
                return ResourceManager.GetString("InfoNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP.
        /// </summary>
        public static string IP {
            get {
                return ResourceManager.GetString("IP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Assinged.
        /// </summary>
        public static string IsAssinged {
            get {
                return ResourceManager.GetString("IsAssinged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        public static string Label {
            get {
                return ResourceManager.GetString("Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest Value.
        /// </summary>
        public static string LatestValue {
            get {
                return ResourceManager.GetString("LatestValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitiude.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location|LocationDetail Management.
        /// </summary>
        public static string LocationAndLocationDetailManagement {
            get {
                return ResourceManager.GetString("LocationAndLocationDetailManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add As Root.
        /// </summary>
        public static string LocationDetailAddAsRoot {
            get {
                return ResourceManager.GetString("LocationDetailAddAsRoot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Detail List.
        /// </summary>
        public static string LocationDetailList {
            get {
                return ResourceManager.GetString("LocationDetailList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationDetail Name.
        /// </summary>
        public static string LocationDetailName {
            get {
                return ResourceManager.GetString("LocationDetailName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocationDetail Type.
        /// </summary>
        public static string LocationDetailType {
            get {
                return ResourceManager.GetString("LocationDetailType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string LocationHeader {
            get {
                return ResourceManager.GetString("LocationHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location List.
        /// </summary>
        public static string LocationList {
            get {
                return ResourceManager.GetString("LocationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Name.
        /// </summary>
        public static string LocationName {
            get {
                return ResourceManager.GetString("LocationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Type.
        /// </summary>
        public static string LocationType {
            get {
                return ResourceManager.GetString("LocationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Type.
        /// </summary>
        public static string LocationTypeName {
            get {
                return ResourceManager.GetString("LocationTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logical Device Name.
        /// </summary>
        public static string LogicalDeviceName {
            get {
                return ResourceManager.GetString("LogicalDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout And Exit.
        /// </summary>
        public static string LogoutAndExit {
            get {
                return ResourceManager.GetString("LogoutAndExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout/Exit.
        /// </summary>
        public static string LogtoutExit {
            get {
                return ResourceManager.GetString("LogtoutExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LoraWan Bus Connection.
        /// </summary>
        public static string LoraWanBusConnection {
            get {
                return ResourceManager.GetString("LoraWanBusConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LTE Bus Connection.
        /// </summary>
        public static string LteBusConnection {
            get {
                return ResourceManager.GetString("LteBusConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mac Address.
        /// </summary>
        public static string MACAddress {
            get {
                return ResourceManager.GetString("MACAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Cards.
        /// </summary>
        public static string ManageCards {
            get {
                return ResourceManager.GetString("ManageCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Catgories.
        /// </summary>
        public static string ManageCategories {
            get {
                return ResourceManager.GetString("ManageCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Unassigned NetworkDevices.
        /// </summary>
        public static string ManageUnassignedNetworkDevice {
            get {
                return ResourceManager.GetString("ManageUnassignedNetworkDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        public static string Manufacturer {
            get {
                return ResourceManager.GetString("Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Text.
        /// </summary>
        public static string MessageText {
            get {
                return ResourceManager.GetString("MessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday.
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Down.
        /// </summary>
        public static string MoveDown {
            get {
                return ResourceManager.GetString("MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Up.
        /// </summary>
        public static string MoveUp {
            get {
                return ResourceManager.GetString("MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MQTT Bus Connection.
        /// </summary>
        public static string MqttBusConnection {
            get {
                return ResourceManager.GetString("MqttBusConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Navigation Card.
        /// </summary>
        public static string NavigationCard {
            get {
                return ResourceManager.GetString("NavigationCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation Card Assigned Sensor.
        /// </summary>
        public static string NavigationCardAssignedSensor {
            get {
                return ResourceManager.GetString("NavigationCardAssignedSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Name.
        /// </summary>
        public static string NavigationCardCardName {
            get {
                return ResourceManager.GetString("NavigationCardCardName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Group.
        /// </summary>
        public static string NavigationCardGroupHeader {
            get {
                return ResourceManager.GetString("NavigationCardGroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation Card Group List.
        /// </summary>
        public static string NavigationCardGroupList {
            get {
                return ResourceManager.GetString("NavigationCardGroupList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation Card List.
        /// </summary>
        public static string NavigationCardList {
            get {
                return ResourceManager.GetString("NavigationCardList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation Category.
        /// </summary>
        public static string NavigationCategory {
            get {
                return ResourceManager.GetString("NavigationCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation Category List.
        /// </summary>
        public static string NavigationCategoryList {
            get {
                return ResourceManager.GetString("NavigationCategoryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigation Category Management.
        /// </summary>
        public static string NavigationCategoryManagement {
            get {
                return ResourceManager.GetString("NavigationCategoryManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Name.
        /// </summary>
        public static string NavigationCategoryName {
            get {
                return ResourceManager.GetString("NavigationCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simcard List.
        /// </summary>
        public static string NetwordDeviceSimcardList {
            get {
                return ResourceManager.GetString("NetwordDeviceSimcardList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Network Device.
        /// </summary>
        public static string NetworkDevice {
            get {
                return ResourceManager.GetString("NetworkDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Identifier.
        /// </summary>
        public static string NetworkDeviceIdentifier {
            get {
                return ResourceManager.GetString("NetworkDeviceIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Device Information.
        /// </summary>
        public static string NetworkDeviceInformation {
            get {
                return ResourceManager.GetString("NetworkDeviceInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Device List.
        /// </summary>
        public static string NetworkDeviceList {
            get {
                return ResourceManager.GetString("NetworkDeviceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Device Managment.
        /// </summary>
        public static string NetworkDeviceManagement {
            get {
                return ResourceManager.GetString("NetworkDeviceManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Device Name.
        /// </summary>
        public static string NetworkDeviceName {
            get {
                return ResourceManager.GetString("NetworkDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Device SubType.
        /// </summary>
        public static string NetworkDeviceSubType {
            get {
                return ResourceManager.GetString("NetworkDeviceSubType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Device Type.
        /// </summary>
        public static string NetworkDeviceType {
            get {
                return ResourceManager.GetString("NetworkDeviceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network Device Usage Information.
        /// </summary>
        public static string NetworkDeviceUsageInformation {
            get {
                return ResourceManager.GetString("NetworkDeviceUsageInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Rule.
        /// </summary>
        public static string NewRule {
            get {
                return ResourceManager.GetString("NewRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Grouped Navigation Card List.
        /// </summary>
        public static string NotGroupedNavigationCardList {
            get {
                return ResourceManager.GetString("NotGroupedNavigationCardList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Noyification Group.
        /// </summary>
        public static string NotificationGroup {
            get {
                return ResourceManager.GetString("NotificationGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Group Data.
        /// </summary>
        public static string NotificationGroupData {
            get {
                return ResourceManager.GetString("NotificationGroupData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification Group Data List.
        /// </summary>
        public static string NotificationGroupDataList {
            get {
                return ResourceManager.GetString("NotificationGroupDataList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Rule.
        /// </summary>
        public static string PauseRule {
            get {
                return ResourceManager.GetString("PauseRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Untill.
        /// </summary>
        public static string PauseRuleUntill {
            get {
                return ResourceManager.GetString("PauseRuleUntill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause until should be bigger than current time.
        /// </summary>
        public static string PauseUntilCouldNotBeAsNow {
            get {
                return ResourceManager.GetString("PauseUntilCouldNotBeAsNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need to Set date for Pause Until.
        /// </summary>
        public static string PauseUntilCouldNotBeNull {
            get {
                return ResourceManager.GetString("PauseUntilCouldNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place Element.
        /// </summary>
        public static string PlaceElement {
            get {
                return ResourceManager.GetString("PlaceElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlanView.
        /// </summary>
        public static string PlanView {
            get {
                return ResourceManager.GetString("PlanView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlanView Management.
        /// </summary>
        public static string PlanViewManagement {
            get {
                return ResourceManager.GetString("PlanViewManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PlanView Name.
        /// </summary>
        public static string PlanViewName {
            get {
                return ResourceManager.GetString("PlanViewName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position X.
        /// </summary>
        public static string PositionX {
            get {
                return ResourceManager.GetString("PositionX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position Y.
        /// </summary>
        public static string PositionY {
            get {
                return ResourceManager.GetString("PositionY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider Name.
        /// </summary>
        public static string ProviderName {
            get {
                return ResourceManager.GetString("ProviderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Category.
        /// </summary>
        public static string RemoveCategory {
            get {
                return ResourceManager.GetString("RemoveCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Filter.
        /// </summary>
        public static string ResetFilter {
            get {
                return ResourceManager.GetString("ResetFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule.
        /// </summary>
        public static string Rule {
            get {
                return ResourceManager.GetString("Rule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule Detail.
        /// </summary>
        public static string RuleDetail {
            get {
                return ResourceManager.GetString("RuleDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule Detail List.
        /// </summary>
        public static string RuleDetailList {
            get {
                return ResourceManager.GetString("RuleDetailList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule Information.
        /// </summary>
        public static string RuleInformation {
            get {
                return ResourceManager.GetString("RuleInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule Management.
        /// </summary>
        public static string RuleManagement {
            get {
                return ResourceManager.GetString("RuleManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule Message text could not be empty.
        /// </summary>
        public static string RuleMessageCouldNotBeEmpty {
            get {
                return ResourceManager.GetString("RuleMessageCouldNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rule name could not be empty.
        /// </summary>
        public static string RuleNameCouldNotBeEmpty {
            get {
                return ResourceManager.GetString("RuleNameCouldNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules.
        /// </summary>
        public static string Rules {
            get {
                return ResourceManager.GetString("Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saturday.
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save new sort number changes.
        /// </summary>
        public static string SaveNewSortChanges {
            get {
                return ResourceManager.GetString("SaveNewSortChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second.
        /// </summary>
        public static string Second {
            get {
                return ResourceManager.GetString("Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Compare Condition List.
        /// </summary>
        public static string SecondCompareConditionList {
            get {
                return ResourceManager.GetString("SecondCompareConditionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Bus Connection Type.
        /// </summary>
        public static string SelectBusConnectionType {
            get {
                return ResourceManager.GetString("SelectBusConnectionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Device.
        /// </summary>
        public static string SelectDevice {
            get {
                return ResourceManager.GetString("SelectDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File.
        /// </summary>
        public static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sensor Management.
        /// </summary>
        public static string SensorManagement {
            get {
                return ResourceManager.GetString("SensorManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number.
        /// </summary>
        public static string SerialNumber {
            get {
                return ResourceManager.GetString("SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Panel View.
        /// </summary>
        public static string SetPanelViewHeader {
            get {
                return ResourceManager.GetString("SetPanelViewHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Details.
        /// </summary>
        public static string ShowDetails {
            get {
                return ResourceManager.GetString("ShowDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim Card Number.
        /// </summary>
        public static string SimCardNumber {
            get {
                return ResourceManager.GetString("SimCardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim card number is not valid.
        /// </summary>
        public static string SimCardNumberIsNotValid {
            get {
                return ResourceManager.GetString("SimCardNumberIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim Card Provider.
        /// </summary>
        public static string SimCardProvider {
            get {
                return ResourceManager.GetString("SimCardProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim card provider is not valid.
        /// </summary>
        public static string SimCardProviderIsNotValid {
            get {
                return ResourceManager.GetString("SimCardProviderIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Number.
        /// </summary>
        public static string SortNumber {
            get {
                return ResourceManager.GetString("SortNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sunday.
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thursday.
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date.
        /// </summary>
        public static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date Every Year.
        /// </summary>
        public static string ToDateEveryYear {
            get {
                return ResourceManager.GetString("ToDateEveryYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Time.
        /// </summary>
        public static string ToTime {
            get {
                return ResourceManager.GetString("ToTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tuesday.
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string UnitMeasurmentName {
            get {
                return ResourceManager.GetString("UnitMeasurmentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username Could Not Be Empty.
        /// </summary>
        public static string UsernameCouldNotBeEmpty {
            get {
                return ResourceManager.GetString("UsernameCouldNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use SSL.
        /// </summary>
        public static string UseSSL {
            get {
                return ResourceManager.GetString("UseSSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid To.
        /// </summary>
        public static string ValidTo {
            get {
                return ResourceManager.GetString("ValidTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning Notification.
        /// </summary>
        public static string WarningNotification {
            get {
                return ResourceManager.GetString("WarningNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wednesday.
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
    }
}
